version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host" #for getting the machine's IP and displaying it
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: saves
      SERVER_PASSWORD: "opusk"

  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saves
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: